version: "3"
services: 
  nginx:
    container_name: mynginx
    image: centos:nginx
    ports:
      - 9090:80
    privileged: true
    volumes:
      - /home/yang/nignx/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      mynginx_web:
        ipv4_address: 192.168.0.5
  web1: 
    container_name: web1
    image: centos:jdk
    ports: 
      - 8080:80
    privileged: true
    volumes: 
      - /home/yang/nignx/web1:/var/www/html
    networks:
      mynginx_web:
        ipv4_address: 192.168.0.4
    healthcheck:
      test: ["CMD", "curl","-s","-f", "http://localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 3

  web2: 
    container_name: web2
    image: centos:jdk
    ports: 
      - 8081:80
    privileged: true
    volumes: 
      - /home/yang/nignx/web2:/var/www/html
    networks:
      mynginx_web:
        ipv4_address: 192.168.0.3
    healthcheck:
      test: ["CMD", "curl","-s","-f", "http://localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  mynginx_web:
    driver: bridge
    ipam: 
      config:
        - subnet: 192.168.0.0/16
