version: "3"
services:
  fpm:
   build:
     context: ./build
     dockerfile: phpredis
   image: php:7.3-fpm-alpine3.9
   container_name: fpm
   volumes:
      - /home/yang/html/web:/php
   networks:
      mywebnet:
       ipv4_address: 192.168.0.2
  httpd:
   image: httpd:2.4-alpine
   container_name: httpd
   ports:
      - 8080:80
   volumes:
      - /home/yang/html/web/public:/usr/local/apache2/htdocs/
      - /home/yang/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
   networks:
      mywebnet:
       ipv4_address: 192.168.0.3
  mysql:
    image: mysql:5.7
    container_name: mysqld
    ports:
      - 3306:3306
    volumes:
      - /home/yang/mysql/conf:/etc/mysql/conf.d
      - /home/yang/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai # 设置时区
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置编码
    networks:
      - mywebnet
  redis:
    image: redis:alpine
    container_name: redis
    ports:
     - 6379:6379
    volumes:
     - /home/yang/html/conf/redis.conf:/usr/local/etc/redis/redis.conf
     - /home/yang/html/redisdata:/data
    networks:
      mywebnet:
       ipv4_address: 192.168.0.10

networks:
  mywebnet:
     driver: bridge
     ipam:
       config:
         - subnet: 192.168.0.0/16

version: "3.6"
services:
  php72:
    image: php
    ports:
        - "9090:9000"
        - "8090:9090"
    volumes:
      -  /usr/docker/php/html:/var/www/html
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    stdin_open: true
    tty: true
    privileged: true
    networks:
        php-network:
          ipv4_address: 172.30.0.7
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
       - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
       - ./mysql:/var/lib/mysql
    stdin_open: true
    tty: true
    privileged: true
    networks:
       mysql-network:
          ipv4_address: 172.50.0.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
networks:
 php-network:
    external:
       name: redis_redis-slave
 mysql-network:
    external:
       name: redis_redis-master
